// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/ecommerce/subscriptions": {
    params: {};
  };
  "/api/ecommerce/subscriptions/manage": {
    params: {};
  };
  "/services/:slug?": {
    params: {
      "slug"?: string;
    };
  };
  "/tools": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/product/:handle": {
    params: {
      "handle": string;
    };
  };
  "/plans": {
    params: {};
  };
  "/subscriptions": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/workspace": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout/success": {
    params: {};
  };
  "/checkout/cancelled": {
    params: {};
  };
  "/llms.txt": {
    params: {};
  };
  "/:section": {
    params: {
      "section": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/ecommerce/subscriptions" | "/api/ecommerce/subscriptions/manage" | "/services/:slug?" | "/tools" | "/products" | "/product/:handle" | "/plans" | "/subscriptions" | "/login" | "/workspace" | "/admin" | "/contact" | "/cart" | "/checkout/success" | "/checkout/cancelled" | "/llms.txt" | "/:section" | "/sitemap.xml" | "/robots.txt" | "/api/health" | "/api/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.ecommerce.subscriptions.ts": {
    id: "routes/api.ecommerce.subscriptions";
    page: "/api/ecommerce/subscriptions";
  };
  "routes/api.ecommerce.subscriptions.manage.ts": {
    id: "routes/api.ecommerce.subscriptions.manage";
    page: "/api/ecommerce/subscriptions/manage";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services/:slug?";
  };
  "routes/tools.tsx": {
    id: "routes/tools";
    page: "/tools";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/product/:handle";
  };
  "routes/plans.tsx": {
    id: "routes/plans";
    page: "/plans";
  };
  "routes/subscriptions.tsx": {
    id: "routes/subscriptions";
    page: "/subscriptions";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/workspace.tsx": {
    id: "routes/workspace";
    page: "/workspace";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.success.tsx": {
    id: "routes/checkout.success";
    page: "/checkout/success";
  };
  "routes/checkout.cancelled.tsx": {
    id: "routes/checkout.cancelled";
    page: "/checkout/cancelled";
  };
  "routes/llms.txt.ts": {
    id: "routes/llms.txt";
    page: "/llms.txt";
  };
  "routes/section.tsx": {
    id: "routes/section";
    page: "/:section";
  };
  "routes/sitemap.xml.ts": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
  "routes/robots.txt.ts": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.$.ts": {
    id: "routes/api.$";
    page: "/api/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/api.ecommerce.subscriptions": typeof import("./src/routes/api.ecommerce.subscriptions.ts");
  "routes/api.ecommerce.subscriptions.manage": typeof import("./src/routes/api.ecommerce.subscriptions.manage.ts");
  "routes/services": typeof import("./src/routes/services.tsx");
  "routes/tools": typeof import("./src/routes/tools.tsx");
  "routes/products": typeof import("./src/routes/products.tsx");
  "routes/product": typeof import("./src/routes/product.tsx");
  "routes/plans": typeof import("./src/routes/plans.tsx");
  "routes/subscriptions": typeof import("./src/routes/subscriptions.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/workspace": typeof import("./src/routes/workspace.tsx");
  "routes/admin": typeof import("./src/routes/admin.tsx");
  "routes/contact": typeof import("./src/routes/contact.tsx");
  "routes/cart": typeof import("./src/routes/cart.tsx");
  "routes/checkout.success": typeof import("./src/routes/checkout.success.tsx");
  "routes/checkout.cancelled": typeof import("./src/routes/checkout.cancelled.tsx");
  "routes/llms.txt": typeof import("./src/routes/llms.txt.ts");
  "routes/section": typeof import("./src/routes/section.tsx");
  "routes/sitemap.xml": typeof import("./src/routes/sitemap.xml.ts");
  "routes/robots.txt": typeof import("./src/routes/robots.txt.ts");
  "routes/api.health": typeof import("./src/routes/api.health.ts");
  "routes/api.$": typeof import("./src/routes/api.$.ts");
};