import { useState } from 'react';
import { Link } from 'react-router';
import { ArrowUpRight, ChevronDown, Menu, ShoppingBag, X } from 'lucide-react';
import { capabilities } from '@/data/company';
import { useAuth } from '@/hooks/use-auth';
import { useCart } from '@/hooks/use-cart';
import { SiteSearch } from '@/components/site-search';
import { menuLinks } from '@/data/navigation';
const navigation = [['Home','/'],['Services','/services'],['Solutions','/solutions'],['Tools','/tools'],['Products','/products'],['Academy','/academy'],['Case Studies','/case-studies'],['Insights','/insights'],['About','/about'],['Contact','/contact']];
export function SiteHeader(){const [open,setOpen]=useState(false);const {isAuthed,isLoading}=useAuth();const {lines,ready}=useCart();return <><a href="#main" className="sr-only-link">Skip to content</a><header className="site-header"><div className="rail header-main"><Link className="logo" to="/">Hello<span>B2C</span><small>DESIGN. DIGITAL. BUSINESS.</small></Link><nav aria-label="Main navigation" className={`nav ${open?'mobile-open':''}`}>{navigation.map(([name,path])=><div className="nav-item" key={name}><Link to={path} onClick={()=>setOpen(false)}>{name}{['Services','Tools','Products','Academy'].includes(name)&&<ChevronDown size={9}/>}</Link>{['Services','Tools','Products','Academy'].includes(name)&&<div className="mega">{name==='Services'?capabilities.map(c=><Link key={c.slug} to={`/services/${c.slug}`}>{c.short} <ArrowUpRight size={11}/></Link>):menuLinks[name]?.map(item=><Link key={item.path} to={item.path}>{item.title}<small style={{display:'block',fontSize:9,color:'var(--quiet)',marginTop:4}}>{item.note}</small></Link>)}</div>}</div>)}</nav><div className="header-actions"><Link to={isAuthed?'/workspace':'/login'}>{isLoading?'Account':isAuthed?'Workspace':'Client Login'}</Link><SiteSearch/><Link to="/cart" aria-label={`Shopping cart ${ready?lines.reduce((s,l)=>s+l.quantity,0):''}`} style={{display:'flex',gap:3}}><ShoppingBag size={15}/>{ready&&lines.length>0&&<span>{lines.reduce((s,l)=>s+l.quantity,0)}</span>}</Link><Link className="button gold" to="/contact">Start a Project <ArrowUpRight size={13}/></Link><button aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} className="mobile-toggle" onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button></div></div></header></>}
